import {cors,db,res,authBranch} from "./edge-shared-branch-auth.ts";
const enc=new TextEncoder(),ADMIN=new Set(["Super Admin","Principal","Admin"]);
function b64(a:Uint8Array){let s="";for(const x of a)s+=String.fromCharCode(x);return btoa(s)}
function unb64(v:string){const s=atob(v),a=new Uint8Array(s.length);for(let i=0;i<s.length;i++)a[i]=s.charCodeAt(i);return a}
async function pbkdf2(p:string,salt:string,it:number){const k=await crypto.subtle.importKey("raw",enc.encode(p),"PBKDF2",false,["deriveBits"]);return b64(new Uint8Array(await crypto.subtle.deriveBits({name:"PBKDF2",salt:unb64(salt),iterations:it,hash:"SHA-256"},k,256)))}
async function passwordRecord(p:string){const salt=b64(crypto.getRandomValues(new Uint8Array(16))),iterations=200000;return{password_salt:salt,password_hash:await pbkdf2(p,salt,iterations),password_iterations:iterations}}
function tempPassword(){const a="ABCDEFGHJKLMNPQRSTUVWXYZabcdefghijkmnopqrstuvwxyz23456789!@#",r=crypto.getRandomValues(new Uint8Array(14));let s="";for(const x of r)s+=a[x%a.length];return s+"aA1!"}
async function clearScopes(userId:string,branchId:string){await Promise.all([db.from("user_departments").delete().eq("branch_id",branchId).eq("user_id",userId),db.from("user_sections").delete().eq("branch_id",branchId).eq("user_id",userId),db.from("user_subjects").delete().eq("branch_id",branchId).eq("user_id",userId)])}
async function setScopes(userId:string,role:string,teacher:any,branchId:string){let departments:string[]=[],sectionIds:string[]=[],subjectIds:string[]=[];if(role==="Admin"){departments=["Telugu","Hindi","English","Mathematics","Physics","Chemistry","Biology","Social","IT"];const[{data:ss},{data:subs}]=await Promise.all([db.from("sections").select("id").eq("branch_id",branchId).eq("active",true),db.from("subjects").select("id").eq("branch_id",branchId).eq("active_for_syllabus",true)]);sectionIds=(ss||[]).map((x:any)=>x.id);subjectIds=(subs||[]).map((x:any)=>x.id)}else if(role==="HOD"){const dept=teacher.syllabus_department;departments=dept?[dept]:[];const{data:subs}=await db.from("subjects").select("id").eq("branch_id",branchId).eq("department",dept).eq("active_for_syllabus",true);subjectIds=(subs||[]).map((x:any)=>x.id);if(subjectIds.length){const{data:maps}=await db.from("teaching_mappings").select("section_id").eq("branch_id",branchId).in("subject_id",subjectIds).eq("active_for_syllabus",true);sectionIds=[...new Set((maps||[]).map((x:any)=>x.section_id))] as string[]}}else{const{data:maps}=await db.from("teaching_mappings").select("section_id,subject_id").eq("branch_id",branchId).eq("teacher_id",teacher.id).eq("active_for_syllabus",true);sectionIds=[...new Set((maps||[]).map((x:any)=>x.section_id))] as string[];subjectIds=[...new Set((maps||[]).map((x:any)=>x.subject_id))] as string[];departments=teacher.syllabus_department?[teacher.syllabus_department]:[]}await clearScopes(userId,branchId);if(departments.length)await db.from("user_departments").insert(departments.map(department=>({branch_id:branchId,user_id:userId,department})));if(sectionIds.length)await db.from("user_sections").insert(sectionIds.map(section_id=>({branch_id:branchId,user_id:userId,section_id})));if(subjectIds.length)await db.from("user_subjects").insert(subjectIds.map(subject_id=>({branch_id:branchId,user_id:userId,subject_id})))}
Deno.serve(async(req:Request)=>{if(req.method==="OPTIONS")return new Response("ok",{headers:cors});try{const a=await authBranch(req);if(!a||!ADMIN.has(a.user.role))return res({error:"Valid branch Admin/Super Admin login required."},401);const branchId=a.branchId,{data:teachers,error}=await db.from("teachers").select("id,name,full_name,employee_id,employee_code,designation,syllabus_department").eq("branch_id",branchId).not("employee_code","is",null).order("full_name");if(error)throw error;const credentials:any[]=[],skipped:any[]=[];for(const t of teachers||[]){const{data:existing}=await db.from("app_users").select("id,username,role").eq("branch_id",branchId).or(`teacher_id.eq.${t.id},employee_code.eq.${t.employee_code}`).maybeSingle();if(existing){await db.from("app_users").update({employee_id:t.employee_id,employee_code:t.employee_code,designation:t.designation}).eq("branch_id",branchId).eq("id",existing.id);skipped.push({name:t.full_name||t.name,reason:"already exists"});continue}const role=t.name==="B. Aruna"?"Admin":/^H\.O\.D\s*\(/i.test(t.designation||"")?"HOD":"Teacher",password=tempPassword(),pw=await passwordRecord(password),username=String(t.employee_code).toUpperCase();const{data:u,error:e}=await db.from("app_users").insert({branch_id:branchId,teacher_id:t.id,name:t.full_name||t.name,username,...pw,role,primary_department:t.syllabus_department||null,access_enabled:true,must_change_password:true,employee_id:t.employee_id,employee_code:t.employee_code,designation:t.designation}).select().single();if(e){skipped.push({name:t.full_name||t.name,reason:e.message});continue}await setScopes(u.id,role,t,branchId);credentials.push({name:t.full_name||t.name,username,password,role,department:t.syllabus_department||"",employee_code:t.employee_code})}return res({ok:true,branch_id:branchId,created:credentials.length,skipped,credentials})}catch(e){console.error(e);return res({error:e?.message||String(e)},400)}});
