const REPO = "umakanthjopwer-beep/syllabus";
const APP_PREFIX = "/functions/v1/syllabus-app/";
const REF = Deno.env.get("SYLLABUS_ASSET_REF") || "main";
const RAW_BASE = `https://raw.githubusercontent.com/${REPO}/${REF}/`;
const MIME:Record<string,string>={html:"text/html; charset=utf-8",js:"application/javascript; charset=utf-8",css:"text/css; charset=utf-8",json:"application/json; charset=utf-8",webmanifest:"application/manifest+json; charset=utf-8",svg:"image/svg+xml",png:"image/png",jpg:"image/jpeg",jpeg:"image/jpeg",ico:"image/x-icon",txt:"text/plain; charset=utf-8"};
function type(path:string){const ext=path.split(".").pop()?.toLowerCase()||"";return MIME[ext]||"application/octet-stream"}
function safePath(url:URL){let p=url.pathname;const i=p.indexOf(APP_PREFIX);p=i>=0?p.slice(i+APP_PREFIX.length):"";p=p.replace(/^\/+/,"");if(!p||p.endsWith("/"))p+="index.html";if(p.includes("..")||p.includes("/")||!/^[-a-zA-Z0-9_.]+$/.test(p))return null;return p}
async function upstream(path:string){return fetch(RAW_BASE+path,{headers:{"User-Agent":"Syllabus-Tracker-Common-App"},cache:"no-store"})}
function headers(path:string){const h=new Headers();h.set("Content-Type",type(path));h.set("X-Content-Type-Options","nosniff");h.set("Referrer-Policy","same-origin");h.set("Cache-Control","no-store, no-cache, must-revalidate, max-age=0");h.set("Cross-Origin-Resource-Policy","same-site");return h}
Deno.serve(async(req:Request)=>{if(req.method!=="GET"&&req.method!=="HEAD")return new Response("Method not allowed",{status:405});const path=safePath(new URL(req.url));if(!path)return new Response("Not found",{status:404});let up=await upstream(path);if(!up.ok&&path!=="index.html")up=await upstream("index.html");if(!up.ok)return new Response("Not found",{status:404});const h=headers(path);if(path!=="index.html"&&up.headers.get("content-type")?.includes("text/html"))h.set("Content-Type","text/html; charset=utf-8");if(path==="index.html"||h.get("Content-Type")?.startsWith("text/html")){let html=await up.text();if(!/<base\s/i.test(html))html=html.replace(/<head(\s[^>]*)?>/i,m=>`${m}\n  <base href="${APP_PREFIX}">`);return new Response(req.method==="HEAD"?null:html,{status:200,headers:h})}return new Response(req.method==="HEAD"?null:up.body,{status:200,headers:h})});