import {cors,db,res} from "./edge-shared-branch-auth.ts";

const enc=new TextEncoder();
function b64(a:Uint8Array){let s="";for(const x of a)s+=String.fromCharCode(x);return btoa(s)}
function unb64(v:string){const s=atob(v),a=new Uint8Array(s.length);for(let i=0;i<s.length;i++)a[i]=s.charCodeAt(i);return a}
async function pbkdf2(p:string,salt:string,it:number){const k=await crypto.subtle.importKey("raw",enc.encode(p),"PBKDF2",false,["deriveBits"]);return b64(new Uint8Array(await crypto.subtle.deriveBits({name:"PBKDF2",salt:unb64(salt),iterations:it,hash:"SHA-256"},k,256)))}
async function passwordRecord(p:string){const salt=b64(crypto.getRandomValues(new Uint8Array(16))),iterations=200000;return{password_salt:salt,password_hash:await pbkdf2(p,salt,iterations),password_iterations:iterations}}
function secureEqual(a:string,b:string){if(a.length!==b.length)return false;let x=0;for(let i=0;i<a.length;i++)x|=a.charCodeAt(i)^b.charCodeAt(i);return x===0}

Deno.serve(async(req:Request)=>{if(req.method==="OPTIONS")return new Response("ok",{headers:cors});if(req.method!=="POST")return res({error:"Method not allowed"},405);try{const configured=Deno.env.get("SUPER_ADMIN_RECOVERY_KEY")||"",provided=req.headers.get("x-recovery-key")||"";if(!configured||!provided||!secureEqual(configured,provided))return res({error:"Recovery authorization required"},403);const b=await req.json().catch(()=>({})),branchCode=String(b.branch_code||"").trim(),username=String(b.username||"").trim(),newPassword=String(b.new_password||"");if(!branchCode||!username)throw new Error("Branch Code and username are required.");if(newPassword.length<12)throw new Error("New password must be at least 12 characters.");const{data:branch}=await db.from("branches").select("id,branch_code,active").ilike("branch_code",branchCode).eq("active",true).maybeSingle();if(!branch)throw new Error("Active branch not found.");const{data:u}=await db.from("app_users").select("id,branch_id,username,role,access_enabled").eq("branch_id",branch.id).ilike("username",username).eq("role","Super Admin").maybeSingle();if(!u||!u.access_enabled)throw new Error("Active Branch Super Admin account not found.");const pw=await passwordRecord(newPassword),now=new Date().toISOString(),{error}=await db.from("app_users").update({...pw,must_change_password:true,bootstrap_recovery_used:true,bootstrap_recovery_attempts:0,updated_at:now}).eq("branch_id",branch.id).eq("id",u.id);if(error)throw error;await db.from("app_sessions").delete().eq("branch_id",branch.id).eq("user_id",u.id);return res({ok:true,branch_code:branch.branch_code,message:"Branch Super Admin password reset. All existing sessions for this account were revoked."})}catch(e){console.error(e);return res({error:e?.message||String(e)},400)}});
