const REMOTE_API="https://sqgytgudepsgucpkecbl.supabase.co/functions/v1/syllabus-api";
const REMOTE_TOKEN_KEY="khalsa_syllabus_api_token";
const REMOTE_TEMP_KEY="khalsa_syllabus_temp_passwords";
let REMOTE={sectionById:new Map(),sectionIdByName:new Map(),subjectById:new Map(),subjectIdByName:new Map(),teacherById:new Map(),teacherIdByName:new Map()};

function remoteToken(){return localStorage.getItem(REMOTE_TOKEN_KEY)||""}
function rememberTemp(userId,password){try{const x=JSON.parse(sessionStorage.getItem(REMOTE_TEMP_KEY)||"{}");x[userId]=password;sessionStorage.setItem(REMOTE_TEMP_KEY,JSON.stringify(x))}catch(e){}}
function tempFor(userId){try{return JSON.parse(sessionStorage.getItem(REMOTE_TEMP_KEY)||"{}")[userId]||""}catch(e){return""}}
async function remoteCall(action,payload={},needsAuth=true){
  const headers={"Content-Type":"application/json"};if(needsAuth){const t=remoteToken();if(!t)throw new Error("Please sign in again.");headers.Authorization=`Bearer ${t}`}
  const r=await fetch(REMOTE_API,{method:"POST",headers,body:JSON.stringify({action,...payload})});let out={};try{out=await r.json()}catch(e){}
  if(!r.ok){if(r.status===401&&needsAuth)localStorage.removeItem(REMOTE_TOKEN_KEY);throw new Error(out.error||`Request failed (${r.status})`)}return out
}
function remoteMap(dataRows){
  REMOTE.sectionById=new Map(dataRows.sections.map(x=>[x.id,x]));REMOTE.sectionIdByName=new Map(dataRows.sections.map(x=>[x.section,x.id]));
  REMOTE.subjectById=new Map(dataRows.subjects.map(x=>[x.id,x]));REMOTE.subjectIdByName=new Map(dataRows.subjects.map(x=>[canonicalSubject(x.name),x.id]));
  REMOTE.teacherById=new Map(dataRows.teachers.map(x=>[x.id,x]));REMOTE.teacherIdByName=new Map(dataRows.teachers.map(x=>[x.name,x.id]));
}
function applyRemoteData(r){
  const ui=data.uiScope||{departments:[],sections:[],subjects:[]};remoteMap(r);
  SECTIONS.splice(0,SECTIONS.length,...r.sections.map(x=>({section:x.section,batch:x.internal_batch,grade:x.grade,program:x.orientation,floor:x.floor})));
  const handling=(r.mappings||[]).map(m=>{const s=REMOTE.sectionById.get(m.section_id),sub=REMOTE.subjectById.get(m.subject_id),t=REMOTE.teacherById.get(m.teacher_id);return{id:m.id,section:s?.section||"",subject:canonicalSubject(sub?.name||""),teacher:t?.name||"",periodsPerWeek:Number(m.periods_per_week||0),week:m.week_pattern||"Every Week",department:sub?.department||"",classTeacher:m.class_teacher||"",coClassTeacher:m.co_class_teacher||"",originalSubject:sub?.name||"",activeForSyllabus:!!m.active_for_syllabus}}).filter(x=>x.section&&x.subject);
  data.setup={...(data.setup||{}),teachers:(r.teachers||[]).map(t=>({id:t.id,name:t.name,department:t.syllabus_department||t.source_department||"",primarySubject:canonicalSubject(t.primary_subject||""),legacyDepartment:t.source_department||""})),handlingMappings:handling,sourceCounts:{classes:r.sections.length,teachers:r.teachers.length,subjects:r.subjects.length,teachingMappings:r.mappings.length},migratedFrom:"Supabase · old app migration"};
  const assigns=new Map();for(const a of r.assignments||[]){if(!assigns.has(a.year_plan_id))assigns.set(a.year_plan_id,[]);const s=REMOTE.sectionById.get(a.section_id);if(s)assigns.get(a.year_plan_id).push(s.section)}
  const weekMap=new Map();for(const w of r.weeks||[]){if(!weekMap.has(w.year_plan_id))weekMap.set(w.year_plan_id,[]);weekMap.get(w.year_plan_id).push({week:`Week ${w.week_no}`,weekNo:w.week_no,startDate:w.start_date||"",endDate:w.end_date||"",workingDays:Number(w.working_days||0),plannedPeriods:Number(w.planned_periods||0),topic:w.topic||""})}
  data.plans=(r.plans||[]).map(p=>{const sub=REMOTE.subjectById.get(p.subject_id),assignedSections=assigns.get(p.id)||[];return{id:p.id,section:assignedSections[0]||"",assignedSections,program:assignedSections[0]?sectionMeta(assignedSections[0]).program:"",programs:[...new Set(assignedSections.map(s=>sectionMeta(s).program))],department:p.department||sub?.department||"",subject:canonicalSubject(sub?.name||""),teacher:"",fileName:p.file_name,fileType:p.file_type||"",size:Number(p.file_size||0),storagePath:p.storage_path||"",enabled:p.enabled!==false,uploadedAt:p.uploaded_at,preview:p.parse_message||"",parseStatus:p.parse_status,weeks:weekMap.get(p.id)||[]}});
  data.weekly=(r.weekly||[]).map(w=>{const s=REMOTE.sectionById.get(w.section_id),sub=REMOTE.subjectById.get(w.subject_id),t=REMOTE.teacherById.get(w.teacher_id);return{id:w.id,week:w.week_label||`Week ${w.week_no||""}`,weekNo:w.week_no,section:s?.section||"",department:sub?.department||"",subject:canonicalSubject(sub?.name||""),teacher:t?.name||"",startDate:w.week_start||"",endDate:w.week_end||"",workingDays:Number(w.working_days||0),plannedPeriods:Number(w.planned_periods||0),takenPeriods:Number(w.periods_taken||0),lagPeriods:Number(w.periods_lagging||0),planned:w.planned_topic||"",actual:w.current_topic||"",reason:w.reason||"",savedAt:w.submitted_at||""}}).filter(x=>x.section&&x.subject);
  const userScopes=r.userScopes||{};
  data.users=(r.users||[]).map(u=>{const sc=userScopes[u.id]||{departments:[],sectionIds:[],subjectIds:[]};return{id:u.id,teacherId:u.teacher_id,name:u.name,username:u.username,role:u.role,department:u.primary_department||"",departments:sc.departments||[],sections:(sc.sectionIds||[]).map(id=>REMOTE.sectionById.get(id)?.section).filter(Boolean),subjects:(sc.subjectIds||[]).map(id=>canonicalSubject(REMOTE.subjectById.get(id)?.name||"")).filter(Boolean),accessEnabled:u.access_enabled!==false,mustChangePassword:!!u.must_change_password}});
  const cs=r.scopes||{departments:[],sectionIds:[],subjectIds:[]};currentUser={id:r.user.id,teacherId:r.user.teacher_id,name:r.user.name,username:r.user.username,role:r.user.role,department:r.user.primary_department||"",departments:cs.departments||[],sections:(cs.sectionIds||[]).map(id=>REMOTE.sectionById.get(id)?.section).filter(Boolean),subjects:(cs.subjectIds||[]).map(id=>canonicalSubject(REMOTE.subjectById.get(id)?.name||"")).filter(Boolean),accessEnabled:r.user.access_enabled!==false,mustChangePassword:!!r.user.must_change_password};
  if(!data.users.some(x=>x.id===currentUser.id))data.users.push({...currentUser});data.uiScope=ui;
  const nameList=document.getElementById("teacherNames");if(nameList)nameList.innerHTML=data.setup.teachers.map(t=>`<option value="${esc(t.name)}"></option>`).join("");
}
async function reloadRemote(){const r=await remoteCall("bootstrap");applyRemoteData(r);return r}
function setBusy(btn,busy,label){if(!btn)return;if(busy){btn.dataset.oldText=btn.textContent;btn.textContent=label||"Saving…";btn.disabled=true}else{btn.textContent=btn.dataset.oldText||btn.textContent;btn.disabled=false}}
function fileToBase64(file){return new Promise((resolve,reject)=>{const rd=new FileReader();rd.onload=()=>resolve(String(rd.result).split(",")[1]||"");rd.onerror=reject;rd.readAsDataURL(file)})}

restoreSession=async function(){
  if(!remoteToken())return;
  try{await reloadRemote();openApp()}catch(e){localStorage.removeItem(REMOTE_TOKEN_KEY);currentUser=null}
};
login=async function(){
  const username=norm($("#loginUsername").value),password=$("#loginPassword").value,btn=$("#loginBtn");if(!username||!password){showLoginError("Enter both username and password.");return}
  setBusy(btn,true,"Signing in…");try{const r=await remoteCall("login",{username,password},false);localStorage.setItem(REMOTE_TOKEN_KEY,r.token);await reloadRemote();$("#loginPassword").value="";openApp()}catch(e){showLoginError(e.message||"Unable to sign in.")}finally{setBusy(btn,false)}
};
logout=async function(){try{if(remoteToken())await remoteCall("logout")}catch(e){}localStorage.removeItem(REMOTE_TOKEN_KEY);sessionStorage.removeItem("khalsa_tracker_user");currentUser=null;$("#appShell").classList.add("hidden");$("#loginScreen").classList.remove("hidden");$("#loginPassword").value=""};

saveWeekly=async function(){
  const section=$("#wkSection").value,subject=canonicalSubject($("#wkSubject").value),btn=$("#saveWeeklyBtn");if(!section||!subject){setStatus("#weeklyStatus","Select class and subject.",true);return}
  const section_id=REMOTE.sectionIdByName.get(section),subject_id=REMOTE.subjectIdByName.get(subject),teacher=handlingTeacher(section,subject)||norm($("#wkTeacher").value),teacher_id=REMOTE.teacherIdByName.get(teacher)||null,plan=visiblePlans().find(p=>p.assignedSections.includes(section)&&p.subject===subject);
  setBusy(btn,true,"Saving…");try{await remoteCall("weekly_save",{week_no:Number(String($("#wkWeek").value).match(/\d+/)?.[0]||0),week_label:$("#wkWeek").value,section_id,subject_id,teacher_id,year_plan_id:plan?.id||null,week_start:$("#wkStart").value||null,week_end:$("#wkEnd").value||null,working_days:Number($("#wkDays").value||0),planned_periods:Number($("#wkPlannedPeriods").value||0),periods_taken:Number($("#wkTakenPeriods").value||0),periods_lagging:Number($("#wkLagPeriods").value||0),planned_topic:norm($("#wkPlanned").value),current_topic:norm($("#wkActual").value),reason:norm($("#wkReason").value)});await reloadRemote();setStatus("#weeklyStatus","Weekly status saved centrally.");renderAll()}catch(e){setStatus("#weeklyStatus",e.message,true)}finally{setBusy(btn,false)}
};
window.deleteWeekly=async id=>{if(!isAdmin()||!confirm("Delete this weekly status record?"))return;try{await remoteCall("weekly_delete",{id});await reloadRemote();renderAll()}catch(e){alert(e.message)}};

savePlan=async function(){
  if(!isAdmin()){setStatus("#planStatus","Only Admin roles can upload Year Plans.",true);return}const file=$("#ypFile").files[0],btn=$("#savePlanBtn");if(!file){setStatus("#planStatus","Select a Year Plan file first.",true);return}
  const section=$("#ypSection").value,department=$("#ypDepartment").value,subject=canonicalSubject($("#ypSubject").value),subject_id=REMOTE.subjectIdByName.get(subject),section_id=REMOTE.sectionIdByName.get(section);if(!subject_id||!section_id){setStatus("#planStatus","Class/subject mapping was not found in the central database.",true);return}
  setBusy(btn,true,"Uploading…");try{const parsed=await parsePlanFile(file);const existing=data.plans.find(p=>p.enabled!==false&&same(p.fileName,file.name)&&same(p.subject,subject));if(existing){const ids=[...new Set([...existing.assignedSections,section].map(s=>REMOTE.sectionIdByName.get(s)).filter(Boolean))];await remoteCall("yearplan_save",{id:existing.id,department,subject_id,section_ids:ids});setStatus("#planStatus",`Existing plan found. ${section} was added to its assignments.`)}else{const file_base64=await fileToBase64(file),weeks=(parsed.weeks||[]).map(w=>({week_no:Number(String(w.week).match(/\d+/)?.[0]||0),week_label:w.week,start_date:/^\d{4}-\d{2}-\d{2}$/.test(w.startDate)?w.startDate:null,end_date:/^\d{4}-\d{2}-\d{2}$/.test(w.endDate)?w.endDate:null,working_days:w.workingDays||null,planned_periods:w.plannedPeriods||null,topic:w.topic||""})).filter(w=>w.week_no);await remoteCall("yearplan_save",{file_name:file.name,file_type:file.type||"application/octet-stream",file_size:file.size,file_base64,department,subject_id,section_ids:[section_id],weeks,parse_status:weeks.length?"parsed":"partial",parse_message:weeks.length?`${weeks.length} week rows detected`:"File stored; week rows not detected automatically"});setStatus("#planStatus",`Uploaded ${file.name} to central storage.`)}$("#ypFile").value="";await reloadRemote();renderAll()}catch(e){setStatus("#planStatus",e.message,true)}finally{setBusy(btn,false)}
};
savePlanEdit=async function(e){
  e.preventDefault();if(!editingPlanId)return;const assigned=$$('#editPlanSections input:checked').map(i=>i.value),btn=$("#planEditForm button[type=submit]");if(!assigned.length){setStatus("#editPlanStatus","Select at least one class/section.",true);return}const department=$("#editPlanDepartment").value,subject=canonicalSubject($("#editPlanSubject").value),subject_id=REMOTE.subjectIdByName.get(subject),section_ids=assigned.map(s=>REMOTE.sectionIdByName.get(s)).filter(Boolean);setBusy(btn,true,"Saving…");try{await remoteCall("yearplan_save",{id:editingPlanId,department,subject_id,section_ids});$("#planEditDialog").close();editingPlanId=null;await reloadRemote();renderAll()}catch(err){setStatus("#editPlanStatus",err.message,true)}finally{setBusy(btn,false)}
};
window.togglePlan=async id=>{if(!isAdmin())return;const p=data.plans.find(x=>x.id===id);if(!p)return;try{await remoteCall("yearplan_save",{id,enabled:p.enabled===false});await reloadRemote();renderAll()}catch(e){alert(e.message)}};
window.deletePlan=async id=>{if(!isAdmin())return;const p=data.plans.find(x=>x.id===id);if(!p||!confirm(`Delete ${p.fileName}? Existing weekly history will remain.`))return;try{await remoteCall("yearplan_delete",{id});await reloadRemote();renderAll()}catch(e){alert(e.message)}};
window.viewPlan=async id=>{try{const r=await remoteCall("yearplan_url",{id});window.open(r.url,"_blank","noopener")}catch(e){alert(e.message)}};
window.downloadPlan=async id=>{try{const r=await remoteCall("yearplan_url",{id});const a=document.createElement("a");a.href=r.url;a.target="_blank";a.rel="noopener";a.click()}catch(e){alert(e.message)}};

addUser=async function(e){
  e.preventDefault();if(!isAdmin())return;const name=norm($("#newUserName").value),username=norm($("#newUsername").value),role=$("#newUserRole").value,department=$("#newUserDepartment").value;if(!name||!username)return;if(data.users.some(x=>same(x.username,username))){alert("Username already exists.");return}
  const maps=teacherMappingsFor(name),selected=data.uiScope||{};let departments=selected.departments?.length?[...selected.departments]:[...new Set(maps.map(m=>m.department).filter(Boolean))],sections=selected.sections?.length?[...selected.sections]:[...new Set(maps.map(m=>m.section))],subjects=selected.subjects?.length?[...selected.subjects]:[...new Set(maps.map(m=>m.subject))];if(role==="HOD"){departments=departments.length?departments:[department];const dm=data.setup.handlingMappings.filter(m=>m.activeForSyllabus&&departments.includes(m.department));sections=selected.sections?.length?sections:[...new Set(dm.map(m=>m.section))];subjects=selected.subjects?.length?subjects:[...new Set(dm.map(m=>m.subject))]}if(ADMIN_ROLES.has(role)){departments=[...DEPARTMENT_ORDER];sections=SECTIONS.map(x=>x.section);subjects=[...ALL_SUBJECTS]}
  try{const r=await remoteCall("user_create",{name,username,role,primary_department:department,departments,section_ids:sections.map(s=>REMOTE.sectionIdByName.get(s)).filter(Boolean),subject_ids:subjects.map(s=>REMOTE.subjectIdByName.get(canonicalSubject(s))).filter(Boolean)});rememberTemp(r.user.id,r.temporary_password);$("#userForm").reset();$("#userDialog").close();data.uiScope={departments:[],sections:[],subjects:[]};await reloadRemote();renderUsers();alert(`User created.\nUsername: ${username}\nTemporary password generated. Use Share to send the login details.`)}catch(err){alert(err.message)}
};
saveUserEdit=async function(e){
  e.preventDefault();if(!isAdmin())return;const u=data.users.find(x=>x.id===editingUserId);if(!u)return;const username=norm($("#editUsername").value),name=norm($("#editUserName").value),role=$("#editUserRole").value,department=$("#editUserDepartment").value,departments=[...document.querySelectorAll(".eu-dept:checked")].map(i=>i.value),sections=[...document.querySelectorAll(".eu-sec:checked")].map(i=>i.value),subjects=[...document.querySelectorAll(".eu-sub:checked")].map(i=>i.value);if(data.users.some(x=>x.id!==u.id&&same(x.username,username))){setStatus("#userEditStatus","Username already exists.",true);return}
  try{await remoteCall("user_update",{user_id:u.id,name,username,role,primary_department:department,departments:ADMIN_ROLES.has(role)?DEPARTMENT_ORDER:departments,section_ids:(ADMIN_ROLES.has(role)?SECTIONS.map(x=>x.section):sections).map(s=>REMOTE.sectionIdByName.get(s)).filter(Boolean),subject_ids:(ADMIN_ROLES.has(role)?ALL_SUBJECTS:subjects).map(s=>REMOTE.subjectIdByName.get(canonicalSubject(s))).filter(Boolean)});editingUserId=null;$("#userEditDialog").close();await reloadRemote();renderUsers()}catch(err){setStatus("#userEditStatus",err.message,true)}
};
window.resetUserPassword=async id=>{if(!isAdmin())return;try{const r=await remoteCall("user_reset_password",{user_id:id});rememberTemp(id,r.temporary_password);await reloadRemote();renderUsers();alert("Temporary password reset. Use Share to send the new login details.")}catch(e){alert(e.message)}};
window.toggleUser=async id=>{if(!isAdmin())return;const u=data.users.find(x=>x.id===id);if(!u)return;try{await remoteCall("user_update",{user_id:id,access_enabled:u.accessEnabled===false});await reloadRemote();renderUsers()}catch(e){alert(e.message)}};
window.deleteUser=async id=>{if(!isAdmin())return;const u=data.users.find(x=>x.id===id);if(!u||!confirm(`Disable access for ${u.name}? Their historical data will be preserved.`))return;try{await remoteCall("user_update",{user_id:id,access_enabled:false});await reloadRemote();renderUsers()}catch(e){alert(e.message)}};
window.shareUser=async id=>{if(!isAdmin())return;const u=data.users.find(x=>x.id===id);if(!u)return;const p=tempFor(id);if(!p){alert("For security, the password is shown only immediately after account creation or password reset. Use Reset Password, then Share.");return}const text=`Sri Chaitanya School – Khalsa CBSE Branch\nSyllabus Tracker Login\n\nName: ${u.name}\nUsername: ${u.username}\nTemporary Password: ${p}\nApp Link: ${appLink()}\n\nPlease change the temporary password after first login and keep it private.`;try{if(navigator.share)await navigator.share({title:"Khalsa Syllabus Tracker Login",text});else if(navigator.clipboard){await navigator.clipboard.writeText(text);alert("Login details copied. Paste them in WhatsApp.")}else prompt("Copy login details",text)}catch(e){}};
savePrivatePassword=async function(e){e.preventDefault();const a=$("#newPrivatePassword").value,b=$("#confirmPrivatePassword").value,err=$("#passwordChangeError");if(a.length<8||a!==b){err.textContent=a!==b?"Passwords do not match.":"Password must contain at least 8 characters.";err.classList.remove("hidden");return}try{await remoteCall("change_password",{password:a});localStorage.removeItem(REMOTE_TOKEN_KEY);err.classList.add("hidden");$("#passwordChangeDialog").close();alert("Password changed. Please sign in again with your new password.");logout()}catch(x){err.textContent=x.message;err.classList.remove("hidden")}};

const _remoteInit=init;
init=function(){_remoteInit();const note=$(".workspace-box small");if(note)note.textContent="Supabase shared database · 2026-27";const sync=$(".sync-pill");if(sync)sync.textContent="LIVE SYNC"};
