plugins {
    id 'com.android.application'
}

android {
    namespace 'com.srichaitanya.khalsasyllabus'
    compileSdk 35

    defaultConfig {
        applicationId 'com.srichaitanya.khalsasyllabus'
        minSdk 23
        targetSdk 35
        versionCode 1
        versionName '1.0.0'
    }

    buildTypes {
        release {
            minifyEnabled false
        }
    }
}
